### ISSUE TITLE
Sometimes uses incorrect environment variable.

### ISSUE THREAD

**Issue by chaulkie** [BachoSeven/mimi#4]
I found that when I used `$TERM` in `mimi.conf`, it was substituting the value of `$COLORTERM` instead of `$TERM`. Looking at the code I found the culprit at line 163:
```sh
app[$i]="$(env | grep "$program" | head -1 | cut -d = -f 2)"
```
`grep "$program"` will match not only the desired variable, but also those which have that variable name as a substring (either of the name or the value). Then `head -1 | cut -d = -f 2` simply grabs the value of the first one listed.

This can be fixed quite simply:
```sh
app[$i]="$(env | grep "^$program=" | head -1 | cut -d = -f 2)"
```

**Comment by BachoSeven** [comment]
Thanks for the heads up, fixing it now!
