### ISSUE TITLE
`$SHELL` should be changed to `sh` or `bash`

### ISSUE THREAD

**Issue by Schweber** [BachoSeven/mimi#6]
I have `nushell` as my user shell, thus the following doesn't work:
```
run() {
  $SHELL -c "'$1' $(printf "%q " "${@:2}")"
}
```
I suggest to change `$SHELL` to `sh` (if that's safe) or `bash`.

**Comment by BachoSeven** [comment]
I could add `SHELL` to the environmental variables parsed from the config, e.g. something like

```
CONFIG_SHELL=$(find_in_config SHELL)
if exists "$CONFIG_SHELL"; then
	TERM=$CONFIG_SHELL
fi
```

and then in the config you could write

```
SHELL: bash
```

What do you think?

**Comment by BachoSeven** [comment]
@Schweber You're right, might as well hardcore it.

**Comment by xplshn** [comment]
> > @Schweber You're right, might as well hardcore it.
> 
> `sh` is the only bin available in $PATH on nix/os, we have to patch anything else usually.

Sounds like an issue with Nix. Usually projects don't adapt for the one and single exception...

**Comment by medv** [comment]
There was not a counterargument provided for making it bash by default, so I think it was worth adding for fairness. It is not an issue, as much as it is worth thinking that bash itself could be considered an opinionated choice under a certain thought process.

**Comment by BachoSeven** [comment]
> It is not an issue, as much as it is worth noting that bash itself could be considered an opinionated choice under a certain thought process.

As much as I might agree with that, the script itself is far from being POSIX-compliant, so I'm definitely not going to make it `#!/bin/sh` for the time being.

Also, I'm not at all an expert with nix but I imagine it is standard to patch bash scripts when packaging, see e.g. https://ertt.ca/nix/shell-scripts/#orgcdf8a6f

**Comment by BachoSeven** [comment]
@Schweber I wasn't responding to you with my last comment, if it wasn't clear from the quote; I was trying to understand @medv's point.
